FROM java:jre

#todo:replace
ENV JAR_STORAGE https://doc-08-0g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fqr8gp7vpd95bm2acsvjcrgn7vfmv8f9/1491552000000/13437062571696576286/*/0B5rjJdkrPLwtRDVBODhHTnF6UGs?e=download

ADD ${JAR_STORAGE} foot-app-server.jar

EXPOSE 8080

CMD java -jar foot-app-server.jar
