---

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main"
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker group is present
  group: name=docker state=present

- name: Add user to Docker group
  user:
    name: "{{ item }}"
    groups: docker
  with_items: "{{ docker_users }}"

- name: Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Docker-py is present
  pip: name=docker-py version={{ docker_py_version }} state=present
  tags: [docker]

- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  tags: [docker]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker]