# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.define :dev do |dev|
    dev.vm.network :forwarded_port, host: 4444, guest: 4444,  host_ip: "127.0.0.1"
    dev.vm.provision "shell", path: "bootstrap.sh"
    dev.vm.provision :shell, inline: 'ansible-playbook /vagrant/.ansible/dev.yml -c local -v'
    dev.vm.hostname = "platform-dev"
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end